### ISSUE TITLE
[Feature 7] Design and Implement Bill Splitter.

### ISSUE THREAD

**Issue by ScottCTD** [CSC207-2022F-UofT/course-project-bill-gates#11]
# Initiations

- In our daily life, we may buy things for multiple individuals to use.
- This raises the question that those related individuals need to pay back some value.
- We define the action of paying back as **split the bill**. 

# Design

- We can treat the data for splitting the bill as a sub-bill of the main bill.
- We define that sub-bill as a **splitter bill**.
- Each entry would have an attribute that refers to the splitter bill.
- Splitter bills would have different columns than normal bills. They should contain information about payees and whether the payee has paid the money back.
- In displaying, after we double-clicked the splitter attribute of an entry, the splitter bill will replace the current bill (main bill).
- We would have a "Back" button to return to the main bill.

# Implementation Details

## Database Specifications

Table Name: `bill_{bill_id}`

Table Specifications:
| Column Name   | Data Type        | Notes                                                        |
| ------------- | ---------------- | ------------------------------------------------------------ |
| `entry_id`    | `INT`            |                                                              |
| `date`        | `TIMESTAMP`      |                                                              |
| `value`       | `DECIMAL(16, 2)` | We expect `value` to have 16 integer places and 2 decimal places. `value` here is the amount of money that the payee needs to pay. |
| `currency`    | `CHAR(3)`        | As defined in ISO 4217, currency codes all have a length of 3 |
| `description` | `TEXT`           |                                                              |
| `from`        | `TEXT`           |                                                              |
| `to`          | `TEXT`           |                                                              |
| `location`    | `TEXT`           |                                                              |
| `payee` | `TEXT` | We may want to change the datatype here. We may not need such a big type here. | 
| `paid_back` | `BOOLEAN` | This represents whether the payee had paid the money back. |

## Related Use Case and Details

- Since we want to replace the entries directly, we may want to call `BillUpdateUseCase`.
- We will set the `currentBill` in the User class as this bill id.
- Every time we clicked the "Back" button, we just change the `currentBill` to the bill id of the main bill of this user, and then call `BillUpdateUseCase`.
- Columns inherited from `AbstractEntry` should have the same values as the parent entry. Inherited columns: `date`, `currency`, `from`, `to`, `location`

# TODOs
- [x] Extend the `UpdateBillUseCase` to this functionality.

## Use Case Update: Insert Entry Use Case

- [x] #51

If you are willing to participate in the development of this feature, please feel free to assign yourself as an assignee.

**Comment by ScottCTD** [comment]
TODO: TODO: https://github.com/CSC207-2022F-UofT/course-project-bill-gates/pull/15#pullrequestreview-1162668971

**Comment by xgao28** [comment]
I'm not sure if I understand how the bill splitter works. From my current thought, it works as one of the following examples:

(1) A, B, C, and D had dinner together and A paid the bill altogether at first, being recorded as an entry in A's bill. Then, A, as a user, decided to split the bill, creating 3 split entries for B, C, and D respectively, and A's bill shows the information on these entries including the amount of money they should pay to A as well as whether they paid back.

(2) A, B, C, and D had dinner together and A paid the bill altogether at first, being recorded as an entry in A's bill. Then, A, as a user, decided to split the bill, creating 3 split entries for B, C, and D respectively in a splitter bill from A, and the splitter bill shows the information on these entries including the amount of money they should pay to A as well as whether they paid back.

If neither (QAQ), is there any example that helps me with this?

**Comment by ScottCTD** [comment]
> I'm not sure if I understand how the bill splitter works. From my current thought, it works as one of the following examples:
> 
> (1) A, B, C, and D had dinner together and A paid the bill altogether at first, being recorded as an entry in A's bill. Then, A, as a user, decided to split the bill, creating 3 split entries for B, C, and D respectively, and A's bill shows the information on these entries including the amount of money they should pay to A as well as whether they paid back.
> 
> (2) A, B, C, and D had dinner together and A paid the bill altogether at first, being recorded as an entry in A's bill. Then, A, as a user, decided to split the bill, creating 3 split entries for B, C, and D respectively in a splitter bill from A, and the splitter bill shows the information on these entries including the amount of money they should pay to A as well as whether they paid back.
> 
> If neither (QAQ), is there any example that helps me with this?

For example, if you paid the bill and there are three people who need to pay some money back.

You opened our software and first created a new entry in your main bill. The value should be the total amount of money you spent. 

Then, you double-clicked the splitter attribute of the entry you just created. A new splitter bill would be created.

In the new splitter bill, you add 3 entries, each specifying which people should pay how much value back.
