### ISSUE TITLE
[Improvement 1] Database Specification

### ISSUE THREAD

**Issue by ScottCTD** [CSC207-2022F-UofT/course-project-bill-gates#22]
- Currently, we need to design 2 types of tables: user tables and bill tables.
# User Table

Table Name: `users`

Table Specifications: 

| Column Name  | Data Type | Notes |
| ------------- | ------------- | ------------- |
| `user_id` | `INT` | |
| `user_name` | 'VARCHAR(10)' | The max user name length is 10 |
| `password` | 'VARCHAR(16)' | The max password length is 16 |
| `bill_id` | `INT` | This is the main bill id of this user |

# Bill Table

Table Name: `bill_{bill_id}`

Side Note: We shouldn't use `user_id` as the `bill_id` because a user may have multiple bills (like many splitter bills)

Table Specifications: 

| Column Name  | Data Type | Notes |
| ------------- | ------------- | ------------- |
| `entry_id` | `INT` | |
| `date` | 'TIMESTAMP' |  |
| `value` | 'DECIMAL(16, 2)' | We expect `value` to have 16 integer places and 2 decimal places |
| `CURRENCY` | `CHAR(3)` | As defined in ISO 4217, currency codes all have a length of 3 |
| `description` | `TEXT` |  |
| `from` | `TEXT` |  |
| `to` | `TEXT` |  |
| `location` | `TEXT` |  |
| 'split_bill_id' | 'INT' | WIP |

@Lei-Tin Please check these specifications and adjust your implementation if needed.

Any suggestions are appreciated.

**Comment by Lei-Tin** [comment]
Understood, will modify and PR in reading week. 
👍
