### ISSUE TITLE
[Bug 1] Missing functionalities of DatabaseGateway

### ISSUE THREAD

**Issue by ScottCTD** [CSC207-2022F-UofT/course-project-bill-gates#42]
- The `DatabaseGateway#getUserData` only gets the usernames and passwords, but we also need the user id and the user's main bill id.
- There should be a insert user method in the DatabaseGateway.

**Comment by Lei-Tin** [comment]
Done fixing the bug, please check [here](https://github.com/CSC207-2022F-UofT/course-project-bill-gates/pull/31) for the update.
