### ISSUE TITLE
[Documentation] Javadoc for UserJoinUseCase @xgao28

### ISSUE THREAD

**Issue by Lei-Tin** [CSC207-2022F-UofT/course-project-bill-gates#55]

**Comment by xgao28** [comment]
了解

**Comment by xgao28** [comment]
This address of this issue needs the completion of #49 though.

**Comment by Lei-Tin** [comment]
> This address of this issue needs the completion of #49 though.

You have 2 choices here, either:
1. Try to write the Javadocs in another branch, and we can take care of the merging conflict when it arises. Or, 
2. Prepare the descriptions of the Javadoc elsewhere, and after #49 is merged, pull out the previously modified Javadoc and add it on. 

The initial description you give will not be too different from each version of the UserJoinUseCase. 

👍

**Comment by xgao28** [comment]
True. Let's get this👍
