### ISSUE TITLE
[Feature 5] Implement Database aspect in the outermost layer.

### ISSUE THREAD

**Issue by ScottCTD** [CSC207-2022F-UofT/course-project-bill-gates#9]

**Comment by ScottCTD** [comment]
TODO: Connect QueryData to entities. @Lei-Tin

**Comment by Lei-Tin** [comment]
> TODO: Connect QueryData to entities. @Lei-Tin

After both of the Pull requests of the Database and Entities are merged to main, I will start working on chaining them together. 

Estimated time of completion would be around the end of Reading week, perhaps. That is, probably around November 14.
